Copium Language: copium::Lexer Class Reference
copium::Lexer Class Reference
Lexer for the Copium programming language.
#include <lexer.hpp>
Public Member Functions
Lexer (std::string source)
Constructs a lexer for the given source code.
Token scanToken ()
Scans the next token from the source code.
std::vector< Token > scanTokens ()
Scans all tokens from the source code.
bool hasError () const
Returns whether the lexer has encountered an error.
const std::vector< std::string > & getErrors () const
Returns the error messages encountered during lexing.
Detailed Description
Lexer for the Copium programming language.
Converts source code into a stream of tokens.
Definition at line 18 of file lexer.hpp.
Constructor & Destructor Documentation
Lexer()
copium::Lexer::Lexer (std::string source) explicit
Constructs a lexer for the given source code.
Parameters
source The source code to be lexed
Definition at line 29 of file lexer.cpp.
Member Function Documentation
getErrors()
const std::vector< std::string > & copium::Lexer::getErrors () const inline
Returns the error messages encountered during lexing.
Returns
A vector of error messages
Definition at line 55 of file lexer.hpp.
hasError()
bool copium::Lexer::hasError () const inline
Returns whether the lexer has encountered an error.
Returns
true if an error has occurred, false otherwise
Definition at line 46 of file lexer.hpp.
scanToken()
Token copium::Lexer::scanToken ()
Scans the next token from the source code.
Returns
The next token
Definition at line 46 of file lexer.cpp.
References copium::AND, copium::ARROW, copium::COLON, copium::COLON_COLON, copium::COMMA, copium::DOT, copium::END_OF_FILE, copium::EQUAL, copium::EQUAL_EQUAL, copium::ERROR, copium::FLOAT_LITERAL, copium::GREATER, copium::GREATER_EQUAL, copium::IDENTIFIER, copium::INTEGER_LITERAL, copium::LEFT_BRACE, copium::LEFT_BRACKET, copium::LEFT_PAREN, copium::LESS, copium::LESS_EQUAL, copium::MINUS, copium::MINUS_EQUAL, copium::NOT, copium::NOT_EQUAL, copium::OR, copium::PERCENT, copium::PLUS, copium::PLUS_EQUAL, copium::RIGHT_BRACE, copium::RIGHT_BRACKET, copium::RIGHT_PAREN, scanToken(), copium::SEMICOLON, copium::SLASH, copium::SLASH_EQUAL, copium::STAR, copium::STAR_EQUAL, and copium::STRING_LITERAL.
Referenced by scanToken(), and scanTokens().
scanTokens()
std::vector< Token > copium::Lexer::scanTokens ()
Scans all tokens from the source code.
Returns
A vector of all tokens in the source code
Definition at line 31 of file lexer.cpp.
References copium::END_OF_FILE, and scanToken().
The documentation for this class was generated from the following files:
lexer.hpp
lexer.cpp